### ISSUE TITLE
Getting Basecamp login page html when trying to access basecamp methods

### ISSUE THREAD

**Issue by sivareddyk** [qpleple/basecamp-python-client#1]
Hi,

We modified the example.py in the following way and try to run the file and we are getting Basecamp login html page. Please have a look at the below lines of code we are using.

bc = Basecamp('https://example.basecamphq.com', 'vamsig@example.com', 'password')
bc.projects()

Please help us in resolving the issue. Looking forward for your reply and thanks in advance.

Regards,
Siva Reddy

**Comment by qpleple** [comment]
Hello Siva,
This project is deprecated, maybe see https://github.com/mativs/basecamp
Cheers
Quentin

**Comment by sivareddyk** [comment]
Hi,

When we are trying to pass the API key we are getting the HTTP Error
401(UnAuthorized error).
EX: bc = Basecamp('https://paraconsult.basecamphq.com', 'API Key') which I
took from the basecamp.

I replaced the API Key with the "base64.encodestring('%s:%s' % (username,
password))" and I am successfully authenticated.

Now I am passing below information but getting Http Error 422
(Unprocessable Entity) while using "create_message()".

project_id = XXXXX
category_id = XXXXXX
title = 'Status for 16/03, 2015'
body = 'This is from Python Script'
notify = [11326745, 10725710]
data = bc.create_message(project_id, category_id, title, body,
notify=notify)

Thanks in advance. Please look into the issue and do the needful.

Regards,
SivaReddy Kothuru.
